load("@requirements//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "packets",
    srcs = glob(["*.py"]),
    visibility = ["//world_server:__subpackages__"],
)
