from construct import Int32ul, Int64ul, Struct, Int32sl, CString, Float32l, Array

from world_server import op_code, router

ClientItemQuerySingle = router.ClientPacket.Register(
    op_code.Client.ITEM_QUERY_SINGLE,
    Struct(
        'entry' / Int32ul,
        'guid' / Int64ul,
    ),
)

ServerItemQuerySingle = Struct(
    'entry' / Int32sl,
    'class_' / Int32sl,
    'subclass' / Int32sl,
    'name' / CString('ascii'),
    'name_2' / CString('ascii'),
    'name_3' / CString('ascii'),
    'name_4' / CString('ascii'),
    'display_info_id' / Int32sl,
    'quality' / Int32sl,
    'flags' / Int32sl,
    'buy_price' / Int32sl,
    'sell_price' / Int32sl,
    'inventory_type' / Int32sl,
    'allowable_class' / Int32sl,
    'allowable_race' / Int32sl,
    'item_level' / Int32sl,
    'required_level' / Int32sl,
    'required_skill' / Int32sl,
    'required_skill_rank' / Int32sl,
    'required_spell' / Int32sl,
    'required_honor_rank' / Int32sl,
    'required_city_rank' / Int32sl,
    'required_reputation_faction' / Int32sl,
    'required_reputation_faction_2' / Int32sl,
    'max_count' / Int32sl,
    'stackable' / Int32sl,
    'container_slots' / Int32sl,
    'stats' / Array(
        10,
        Struct(
            'type' / Int32sl,
            'value' / Int32sl,
        ),
    ),
    'damages' / Array(
        5,
        Struct(
            'min' / Float32l,
            'max' / Float32l,
            'type' / Int32sl,
        ),
    ),
    'armor' / Int32sl,
    'holy_res' / Int32sl,
    'fire_res' / Int32sl,
    'nature_res' / Int32sl,
    'frost_res' / Int32sl,
    'shadow_res' / Int32sl,
    'arcane_res' / Int32sl,
    'delay' / Int32sl,
    'ammo_type' / Int32sl,
    'ranged_mod_range' / Float32l,
    'spells' / Array(
        5,
        Struct(
            'id' / Int32sl,
            'trigger' / Int32sl,
            'charges' / Int32sl,
            'cooldown' / Int32sl,
            'category' / Int32sl,
            'category_cooldown' / Int32sl,
        ),
    ),
    'bonding' / Int32sl,
    'description' / CString('ascii'),
    'page_text' / Int32sl,
    'language_id' / Int32sl,
    'page_material' / Int32sl,
    'start_quest' / Int32sl,
    'lock_id' / Int32sl,
    'material' / Int32sl,
    'sheath' / Int32sl,
    'random_property' / Int32sl,
    'block' / Int32sl,
    'item_set' / Int32sl,
    'max_durability' / Int32sl,
    'area' / Int32sl,
    'map' / Int32sl,
    'bag_family' / Int32sl,
)
