load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "enums",
    srcs = [
        "__init__.py",
        "generated.py",
        "static.py",
    ],
    visibility = ["//visibility:public"],
)
