name: Unit Tests
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Setup environment
        run: pip install wheel && pip install -r requirements.txt
      - name: Run Tests
        run: python -m pytest test
  
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Setup environment
        run: pip install wheel && pip install -r requirements.txt
      - name: Generate coverage report
        run: python -m pytest test --cov=.
      - name: Upload coverage reports
        run: |
          pip install codecov
          codecov --token="${CODECOV_UPLOAD_TOKEN?}"
        env:
          CODECOV_UPLOAD_TOKEN: ${{ secrets.CODECOV_UPLOAD_TOKEN }}

