name: Unit Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.cache/bazel
          key: ${{ runner.os }}-bazel
      - name: Run Tests (Windows)
        if: matrix.os == 'windows'
        run: ./bazel.exe test //...
      - name: Run Tests
        if: matrix.os != 'windows'
        run: bazel test --test_output=errors //...
