name: Unit Tests
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: macos-latest
          BAZEL_BIN: bazel
        - os: ubuntu-latest
          BAZEL_BIN: bazel
        - os: windows-latest
          BAZEL_BIN: bazel.exe
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.cache/bazel
          key: ${{ runner.os }}-bazel
      - name: Run Tests
        run: ./${{ matrix.BAZEL_BIN }} --output_user_root="${{ github.workspace }}/.cache/bazel" test //...
